from dataclasses import dataclass

@dataclass
class TrackerRequest:
    """
    Attributes:
        info_hash (str): Urlencoded 20-byte SHA1 hash of the value of the info key from the Metainfo file.
        peer_id: (str) urlencoded 20-byte string used as a unique ID for the client, generated by the client at startup.
        port (int): The port number that the client is listening on.
        uploaded (int): The total amount uploaded  in base ten ASCII.
        downloaded (int): The total amount downloaded in base ten ASCII.
        left (int) : The number of bytes this client still has to download in base ten ASCII.
        compact (int): Setting this to 1 indicates that the client accepts a compact response.
        no_peer_id (int): Indicates that the tracker can omit peer id field in peers dictionary.
        event (str): If specified, must be one of "started", "completed", "stopped".
            "started": The first request to the tracker must include the event key with this value.
            "stopped": Must be sent to the tracker if the client is shutting down gracefully.
            "completed": Must be sent to the tracker when the download completes.
        ip (str): (Optional). The true IP address of the client machine.
        numwant (int): (Optional). Number of peers that the client would like to receive from the tracker. This value is permitted to be zero.
        key (str) : (Optional). An additional identification that is not shared with any other peers. It is intended to allow a client to prove their identity should their IP address change.
        trackerid (str): (Optional). If a previous announce contained a tracker id, it should be set here.
    """
    info_hash: str
    peer_id: str
    port: int
    uploaded: int
    downloaded: int
    left: int
    compact: int
    no_peer_id: int
    event: str
    ip: str
    numwant: int
    key: str
    trackerid: str
